version: '3'
services:

  web:
    container_name: web
    image: yexxi/docker-web
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul

  nginx:
    container_name: nginx
    image: yexxi/docker-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - TZ=Asia/Seoul

  mysql:
    container_name: mysql
    image: yexxi/docker-mysql
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "3306:3306"
    # 환경 변수 설정
    environment:
      MYSQL_ROOT_PASSWORD: yexxi2118#
      TZ: Asia/Seoul
    # 명렬어 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    # 볼륨 설정
    volumes:
       - ./data/mysql/:/var/lib/mysql

